### Usage of role in the Main playbooks
# - name: deploy files
#   hosts: webapp
#   tasks:
#     - include_role:
#           name: Deploy
#       any_errors_fatal: true

### Parameter List
- name: files
  file: path=/var/www/html state=absent
- 
  file: path=/var/www/html state=directory
- 
  name: Deploy war Apache2
  copy:
    src: files/myweb-0.0.4.war
    dest: /var/www/html/myweb-0.0.4.war
- 
  name: unzip war
  unarchive:
     src: /var/www/html/myweb-0.0.4.war
     dest: /var/www/html/
     remote_src: yes
