---
- name: Starting the deployment
  become: true
  become_method: sudo
  hosts: webapp
  gather_facts: false
  tasks:
   - name: Include role for apache installation
     include_role:
         name: installApache
